spring:
  application:
    name: api-wallet

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # ou "create-drop", "validate", "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: false