server:
  port: 8080
  servlet:
    context-path: /api-example

spring:
  application:
    name: api-example
  datasource:
    url: 'jdbc:postgresql://localhost:5432/example?application_name=application-primary'
    url-replica: 'jdbc:postgresql://localhost:5432/example?application_name=application-replica'
    username: 'example'
    password: 'example'
    driver-class-name: 'org.postgresql.Driver'
    hikari:
      primary:
        maximum-pool-size: 10
        connection-timeout: 30000
        minimum-idle: 2
        idle-timeout: 60000
        max-lifetime: 180000
        leak-detection-threshold: 0
        validation-timeout: 5000
        pool-name: application-primary
      replica:
        maximum-pool-size: 15
        connection-timeout: 30000
        minimum-idle: 3
        idle-timeout: 60000
        max-lifetime: 180000
        leak-detection-threshold: 0
        validation-timeout: 5000
        pool-name: application-replica
  jpa:
    hibernate:
      ddl-auto: create-drop # ou "create-drop", "validate", "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: false